1-module_tasks Done
js-tasks-ru/jsbasic-20210201_garlex pull request #2
Opened 2021-02-15 19:52 UTC by Garlex

2021-02-15 19:52 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-02-16 16:51 UTC, koalex requested changes

2021-02-16 16:51 UTC, koalex commented on 1-module/1-task/index.js
> +  if (n < 1) {
тут нужно ещё добавить проверку на ноль. Если ноль, то тоже вернуть 1

2021-02-16 17:01 UTC, koalex approved these changes

2021-02-16 17:02 UTC, merged